import type {Compiler, WebpackPluginInstance} from "webpack";
import glob from "fast-glob";
import fs from "fs";
import path from "path";

export class ReactGenImageComponentsPlugin implements WebpackPluginInstance {
    private imagePath: string;
    private projectRoot: string;

    constructor(imagePath: string, projectRoot: string)
    {
        this.imagePath = imagePath;
        this.projectRoot = projectRoot;
    }

    public apply(compiler: Compiler){
        compiler.hooks.beforeCompile.tap("ImageRecordPlugin", () =>
        {
            const imageFiles = glob.sync(`${this.imagePath}/**/*.{png,jpg,jpeg,gif,svg}`, {
                cwd: process.cwd(),
            });
            
            const comments = [`// This file is auto-generated by ImageRecordPlugin. manual edits will be lost\n`];

            const folderDestination = path.join(this.projectRoot, "src", "generatedImageComponents");
            fs.rmSync(folderDestination, { recursive: true, force: true });
            fs.mkdirSync(folderDestination, { recursive: true });

            for (const file of imageFiles)
            {
                const fileName = file.split("/").pop()?.split(".")[0] as string;
                const imageImportString = `import ${fileName} from "../../${file}";`;

                const tsContents = `${imageImportString}
import {ImgHTMLAttributes} from "react";

${comments.join("\n").slice(0, -1)}
export const ${fileName}Image = (props: ImgHTMLAttributes<HTMLImageElement>) =>
{
    return (
        <img src={${fileName}} {...props}/>
    )
}`;

                const tsPath = `${folderDestination}/${fileName}Image.tsx`;
                
                fs.writeFileSync(tsPath, tsContents);
            }
        });
    }
}