import type {Compiler, WebpackPluginInstance} from "webpack";
import glob from "fast-glob";
import fs from "fs";
import path from "path";

export class ReactGenImageComponentsPlugin implements WebpackPluginInstance {
    private imagePath: string;
    private projectRoot: string;

    constructor(imagePath: string, projectRoot: string)
    {
        this.imagePath = imagePath;
        this.projectRoot = projectRoot;
    }

    public apply(compiler: Compiler){
        compiler.hooks.beforeCompile.tap("ImageRecordPlugin", () =>
        {
            const imageFiles = glob.sync(`${this.imagePath}/**/*.{png,jpg,jpeg,gif,svg}`, {
                cwd: process.cwd(),
            });
            
            console.log("Image path: ", this.imagePath);
            console.log("image files: ", imageFiles);
            const comments = [`// This file is auto-generated by ImageRecordPlugin. manual edits will be lost\n`];

            for (const file of imageFiles)
            {
                const fileName = file.split("/").pop()?.split(".")[0] as string;
                const imageImportString = `import ${fileName} from "../../${file}";`;

                const tsContents = `${imageImportString}

${comments.join("\n").slice(0, -1)}
export const ${fileName}Image = () =>
{
    return (
        <img src={${fileName}} />
    )
}`;

                const folderDestination = path.join(this.projectRoot, "node_modules", ".cache", "generatedImageComponents");
                fs.mkdirSync(folderDestination, { recursive: true });

                const tsPath = `${folderDestination}/${fileName}Image.tsx`;
                console.log("ts path: ", tsPath);
                
                fs.writeFileSync(tsPath, tsContents);
            }
        });
    }
}